language: android
jdk: oraclejdk7
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - addon-google_apis-google-23
env:
  global:
  - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
before_install:
- openssl aes-256-cbc -K $encrypted_8745c88362bd_key -iv $encrypted_8745c88362bd_iv
  -in app.jks.enc -out app.jks -d
script:
  - ./gradlew app:assembleRelease -x lintVitalRelease
deploy:
  provider: releases
  api_key:
    secure: 3BmX4oyxKOl7wQQZ0GXw2M5wrcmKX3610W9nPtw1G56tBWvpjYTam8W7+xvzajQtaD2uNym52AqwnFBodNmNzZFwNxlulIDWoWgYv0tl59FrrNabMQaKRWeqmeME4QU23dYNJshQXNsmLSBKdyZJFP9FJgLkIlPjuHxr9/0jU1kaQl0wKzS2PA0LeLmPano6izdRniw8eASQ4PYLtPe5w/6rZM1YSiV5Rdn0vCreGet5FBUizaRi6AqgMdjidK5EfbZ+Zjo3nM05JR/2tEFd6C+SAWSVzEr9JIGY7giJcZAHmett1xObK9DQCGXq2Y4Qn5ZKplIjm1n3xOF6jW5RAnlVMJQJl6f/Bl04/L3+LHl3fc/LjR34CLcwxk/FMUTDp9ApsJ/KjFBz+D4EEC+ke+YNVjVTVJq++kRXeZiWSIkiWBIVL1XfNA65rrx5IUxKQ+9nq0W98zJwOTzoucxZW5Tx6yjDVU1dI0nIYeOyTn6Fij9yF/Q16TW3mO4dZcPfslghHTj45v4c8+CF2mgziAvNG36G3O6IkY4Z3jMtGkm6PibY0TCvjfMswOdJHufUTFkxaBKbuEIRTV+DOA8sM0eTdp18mBTFrmnk7hgqOcr9ZxEeiOuaD2i7uKw5JaAt2tW1lhEjKcrMGPD/W3WEBOz32D6owFkKAKpvvmSfhOo=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: drunlin/guokr-android
    tags: true
